#!/usr/bin/python3
# 杨辉三角定义如下：
#
#           1
#          / \
#         1   1
#        / \ / \
#       1   2   1
#      / \ / \ / \
#     1   3   3   1
#    / \ / \ / \ / \
#   1   4   6   4   1
#  / \ / \ / \ / \ / \
# 1   5   10  10  5   1
# 把每一行看做一个list，试写一个generator，不断输出下一行的list：


def triangles():
    before = [1]
    after = []
    while True:
        yield before
        before, after = [1] + after + [1], []
        for i in range(len(before) - 1):
            after.append(before[i] + before[i + 1])


tri = triangles()
for num in range(10):
    print(next(tri))
